# Generated by Django 6.0.3 on 2026-03-26 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('position', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('attacker', 'Attacker')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
            ],
            options={
                'db_table': 'players',
                'ordering': ['position', 'last_name'],
            },
        ),
    ]
