# Generated by Django 6.0.3 on 2026-03-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='team.team'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position'], name='players_positio_0bd0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team'], name='players_team_id_483bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['value'], name='players_value_b21144_idx'),
        ),
    ]
