# Generated by Django 6.0.3 on 2026-03-26 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listing', to='player.player')),
            ],
            options={
                'db_table': 'transfer_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
