# Generated by Django 6.0.3 on 2026-03-26 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transferlisting',
            index=models.Index(fields=['is_active', 'created_at'], name='transfer_li_is_acti_1a68b7_idx'),
        ),
    ]
